name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
      
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      
      - name: Install Android SDK
        run: |
          sdkmanager --list
          sdkmanager --install "platforms;android-28"
          sdkmanager --install "build-tools;28.0.3"
          sdkmanager --install "ndk;21.1.6352462"

      - name: Build the project
        run: |
          zig build keystore install 
